# Generated by Django 4.0.3 on 2022-04-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-is_done', '-created_at']},
        ),
    ]
