# Generated by Django 4.0.3 on 2022-04-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_task_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(related_name='tasks', to='app.tag'),
        ),
    ]
