# Generated by Django 4.0.3 on 2022-04-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_task_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tag',
            new_name='tags',
        ),
    ]
